import type { Mosque } from "@/lib/types";

export const seedMosques: Mosque[] = [
  {
    id: "masjid-al-noor",
    name: "Jama Masjid Mumbai",
    address: "52 Mandai Street, Fort, Mumbai",
    lat: 18.9596,
    lng: 72.8295,
    phone: "+91 22 2261 9313",
    timings: {
      fajr: "05:45 AM",
      sunrise: "06:33 AM",
      dhuhr: "12:35 PM",
      asr: "04:10 PM",
      maghrib: "06:34 PM",
      isha: "08:05 PM",
      jumuah: "01:15 PM",
    },
    created_at: new Date().toISOString(),
    owner_id: null,
    city: "Fort",
    description: "Historic mosque in South Mumbai with daily congregation and Friday khutbah.",
    facilities: ["Parking", "Women prayer area", "Wudu area", "Wheelchair access"],
    photos: ["/mosque-placeholder-1.svg", "/mosque-placeholder-2.svg"],
  },
  {
    id: "masjid-ar-rahman",
    name: "Masjid Ar-Rahman",
    address: "234 Bandra Reclamation, Bandra West, Mumbai",
    lat: 19.0596,
    lng: 72.8295,
    phone: "+91 22 5645 8923",
    timings: {
      fajr: "05:42 AM",
      sunrise: "06:30 AM",
      dhuhr: "12:33 PM",
      asr: "04:08 PM",
      maghrib: "06:32 PM",
      isha: "08:03 PM",
      jumuah: "01:20 PM",
    },
    created_at: new Date().toISOString(),
    owner_id: null,
    city: "Bandra",
    description: "Community mosque with learning center and wudu facilities.",
    facilities: ["Parking", "Learning center", "Wudu area", "Women prayer area"],
    photos: ["/mosque-placeholder-3.svg"],
  },
  {
    id: "community-islamic-center",
    name: "Islamic Foundation Andheri",
    address: "45 Veera Desai Road, Andheri West, Mumbai",
    lat: 19.1136,
    lng: 72.8194,
    phone: "+91 22 2623 4567",
    timings: {
      fajr: "05:44 AM",
      sunrise: "06:32 AM",
      dhuhr: "12:34 PM",
      asr: "04:09 PM",
      maghrib: "06:33 PM",
      isha: "08:04 PM",
      jumuah: "01:10 PM",
    },
    created_at: new Date().toISOString(),
    owner_id: null,
    city: "Andheri",
    description: "Family-friendly center with weekend classes and community services in West Mumbai.",
    facilities: ["Women prayer area", "Wheelchair access", "Library", "Parking"],
    photos: ["/mosque-placeholder-4.svg"],
  },
  {
    id: "masjid-an-nur",
    name: "Masjid An-Nur Dadar",
    address: "78 Dr Ambedkar Road, Dadar East, Mumbai",
    lat: 19.0185,
    lng: 72.8388,
    phone: "+91 22 2414 9823",
    timings: {
      fajr: "05:43 AM",
      sunrise: "06:31 AM",
      dhuhr: "12:34 PM",
      asr: "04:09 PM",
      maghrib: "06:33 PM",
      isha: "08:04 PM",
      jumuah: "01:25 PM",
    },
    created_at: new Date().toISOString(),
    owner_id: null,
    city: "Dadar",
    description: "Beautiful mosque with courtyard and evening Quran study circle.",
    facilities: ["Courtyard", "Wudu area", "Parking", "Library"],
    photos: ["/mosque-placeholder-5.svg"],
  },
];